---
kind: Service
apiVersion: v1
metadata:
  name: tiddles
spec:
  selector:
    app: tiddles
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: grpc
    protocol: TCP
    port: 50000
    targetPort: 50000
  type: NodePort
  externalTrafficPolicy: Local # or Cluster

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiddles-dep
  labels:
    deployment: tiddles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiddles
  template:
    metadata:
      labels:
        app: tiddles
    spec:
      containers:
      # [START app_container]
      - name: tiddles
        image: gcr.io/nmiu-play/tiddles
        imagePullPolicy: Always
        args:
          - -cert=/tls/tls.crt
          - -key=/tls/tls.key
        env:
        - name: MONGODB_URL
          value: mongodb
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: grpc
          containerPort: 50000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      # [START app_container]
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb 27017; do sleep 2; done']

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-dep
  labels:
    deployment: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb 
        image: gcr.io/nmiu-play/mongodb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongo
          protocol: TCP
          containerPort: 27017
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
            ephemeral-storage: 2Gi
          limits:
            cpu: 300m
            memory: 1Gi
            ephemeral-storage: 2Gi