---
apiVersion: v1
kind: Service
metadata:
  name: tiddles-frontend
spec:
  selector:
    app: tiddles
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http-oczpages
    protocol: TCP
    port: 8888
    targetPort: 8888
  - name: grpc
    protocol: TCP
    port: 50000
    targetPort: 50000
  type: NodePort
  externalTrafficPolicy: Local # or Cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiddles-frontend
  labels:
    app: tiddles
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiddles
      tier: frontend
  template:
    metadata:
      labels:
        app: tiddles
        tier: frontend
    spec:
      containers:
      # [START app_container]
      - name: tiddles
        image: gcr.io/nmiu-play/tiddles
        imagePullPolicy: Always
        args:
          - /tiddles
          - --cert=/tls/tls.crt
          - --key=/tls/tls.key
          - --trace
          - --backend=tiddles-backend:80
          - --grpc-backend=tiddles-backend:50000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: http-oczpages
          containerPort: 8888
          protocol: TCP
        - name: grpc
          containerPort: 50000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      # [END app_container]

---
apiVersion: v1
kind: Service
metadata:
  name: tiddles-backend
spec:
  selector:
    app: tiddles
    tier: backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http-oczpages
    protocol: TCP
    port: 8888
    targetPort: 8888
  - name: grpc
    protocol: TCP
    port: 50000
    targetPort: 50000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiddles-backend
  labels:
    app: tiddles
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiddles
      tier: backend
  template:
    metadata:
      labels:
        app: tiddles
        tier: backend
    spec:
      containers:
      # [START app_container]
      - name: tiddles
        image: gcr.io/nmiu-play/tiddles
        imagePullPolicy: Always
        args:
          - /tiddles
          - --cert=/tls/tls.crt
          - --key=/tls/tls.key
          - --trace
        env:
        - name: MONGODB_URL
          value: mongodb
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: http-oczpages
          containerPort: 8888
          protocol: TCP
        - name: grpc
          containerPort: 50000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      # [END app_container]
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb 27017; do sleep 2; done']

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: gcr.io/nmiu-play/mongodb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongo
          protocol: TCP
          containerPort: 27017
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
            ephemeral-storage: 2Gi
          limits:
            cpu: 300m
            memory: 1Gi
            ephemeral-storage: 2Gi
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - echo 'db.runCommand("ping").ok' | mongo localhost/test --quiet
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - echo 'db.runCommand("ping").ok' | mongo localhost/test --quiet